#!/usr/bin/env bash
mkdir -p dist
echo "build src/index.ls -> dist/ldpage.js ..."
./node_modules/.bin/lsc -cbp src/index.ls > dist/ldpage.js
echo "minifying ldpage.js ..."
./node_modules/.bin/uglifyjs dist/ldpage.js > dist/ldpage.min.js
echo "done."
