#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldpage.ls -> dist/ldpage.js ..."
npx lsc -cp src/ldpage.ls > dist/ldpage.js
echo "minifying ldpage.js ..."
npx uglifyjs dist/ldpage.js > dist/ldpage.min.js
echo "copy dist to web ..."
rm -rf web/static/assets/lib/ldpage/dev/
mkdir -p web/static/assets/lib/ldpage/dev/
cp -R dist/* web/static/assets/lib/ldpage/dev/
echo "done."
